apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: getshorty
spec:
  promotionFlows:
    - name: test1
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '*'
  promotionTemplate:
    versionSource:
      file: app-service.yaml
      jsonPath: $.*.*.*.nodePort
    promotion:
      app-deploy.yaml:
        jsonPaths:
          - $.*.replicas
  concurrency: queue
