apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: getshorty
spec:
  promotionFlows:
    - name: test1
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '*promotion*'
  concurrency: queue
