gitops-runtime:
  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          archiveLogs: true
          artifactRepositoryRef:
            configMap: codefresh-workflows-log-store
            key: codefresh-workflows-log-store
  global:
    codefresh:
      accountId: 68ac196ce9300614fec29f36
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh-minikube
  argo-cd:
    configs: 
      # url: http://localhost:8080
      cm: 
        url: http://localhost:8080
        oidc.config: |
          name: ldap
          issuer: http://localhost:8080/api/dex
          clientID: argo-cd
          clientSecret: 4Gcl1Wqv1UDdEgqiqBGzJg7MasF_gp24xHcQD6bO
          requestedScopes:
          - openid
          - profile
          - email
          - groups
          insecureSkipVerify: true
        dex.config: |
          issuer: http://localhost:8080/api/dex
          staticClients:
          - id: argo-cd
            redirectURIs:
            - http://localhost:8080/api/dex/callback
            - http://localhost:8080/auth/callback
            name: Argo CD
            secret: 4Gcl1Wqv1UDdEgqiqBGzJg7MasF_gp24xHcQD6bO
            trustedPeers:
            - argo-cd-cli
            - argo-cd-pkce
          - id: argo-cd-cli
            redirectURIs:
            - http://localhost:8085/auth/callback
            name: Argo CD CLI
            public: true
          - id: argo-cd-pkce
            redirectURIs: 
            - http://localhost:8085/auth/callback
            name: Argo CD PKCE
            public: true
          logger:
            level: info
            format: json
          connectors:
          - type: ldap
            id: ldap 
            name: OpenLDAP
            config:
              host: "172.23.82.72:389" 
              insecureNoSSL: true
              bindDN: "cn=admin,dc=myorg,dc=local"
              bindPW: "admin"
              userSearch:
                baseDN: "dc=myorg,dc=local"
                filter: "(objectClass=inetOrgPerson)"
                username: uid
                idAttr: uid
                emailAttr: mail
                nameAttr: cn
            
