gitops-runtime:
  global:
    codefresh:
      accountId: 682ec6b9fe4d320445de17c2
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
