apiVersion: codefresh.io/v1beta1
kind: RestrictedGitSource
metadata:
  name: restricted-test
spec:
  source:
    repoURL: https://github.com/maryia-brauer/secure-cd-fork.git
    path: .
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destinations:
  - server: '*'
    name: '*'
    namespace: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  sourceRepos:
  - '*'
  sourceNamespace: 'cf-test'
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
